### ISSUE TITLE
Task Failed - ConnectTimeoutError: Connect Timeout Error

### ISSUE THREAD

**Issue by ColdbloodDK** [OutwalkStudios/discord-backup#17] opened 2023-09-27 00:30 UTC
The bot have full permission (Administrator)
and this intents: 
```
intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers,
  ],
```
Error:
```
:warning: All the server channels, roles, and settings will be cleared. Do you want to continue? Send `-confirm` or `cancel`!
Error occurred while deleting roles: Missing Permissions
FAILED: fetch failed
TASK: {"args":[],"options":{"priority":5,"weight":1,"expiration":null,"id":"<no-id>-xrwn4le464"},"retryCount":0}
TypeError: fetch failed
    at fetch (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataResolver.resolveFile (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\util\DataResolver.js:125:21)
    at async DataResolver.resolveImage (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\util\DataResolver.js:68:18)
    at async GuildChannelManager.createWebhook (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\managers\GuildChannelManager.js:220:16) {       
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:182:24)
      at D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:129:46
      at Immediate._onImmediate (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:168:33)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

```

**Comment by jleeson** [comment] 2023-09-27 00:44
Hey @ColdbloodDK, would you mind providing some code to reproduce this error? Typically the missing permissions error  while deleting roles occurs when the auto created bot role is listed below a role that it needs to be able to delete. administrator permission does not override this requirement.

I would be happy to do some testing and look into whats causing this error if you can provide some code to reproduce the error and double check that the bot role is above all other roles.

**Comment by ColdbloodDK** [comment] 2023-09-27 02:49
Resolved the missing permission error but i get anyway the timeout:
```
FAILED: fetch failed
TASK: {"args":[],"options":{"priority":5,"weight":1,"expirat
ion":null,"id":"<no-id>-l4ed8b5v3jc"},"retryCount":0}       
TypeError: fetch failed
    at fetch (D:\Progetti\Software\Discord\discord-backupper
\node_modules\undici\index.js:109:13)
    at process.processTicksAndRejections (node:internal/proc
ess/task_queues:95:5)
    at async DataResolver.resolveFile (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\util\DataResolver.js:125:21)
    at async DataResolver.resolveImage (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\util\DataResolver.js:68:18)
    at async Guild.edit (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\structures\Guild.js:854:24) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:182:24)
      at D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:129:46
      at Immediate._onImmediate (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:168:33)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```
The bot code is the same as the template from the og repository, the backup function is this,
``` 
backup.load(backupID, message.guild, {
                  clearGuildBeforeRestore: true,
                  maxMessagesPerChannel: 1000,
                  speed: 10000,
              }).then(() => {

                  return console.log('Backup loaded successfully!');
          
              }).catch((err) => {
          
                  if (err === 'No backup found')
                      return console.log(':x: No backup found for ID '+backupID+'!');
                  else
                      return console.log(':x: An error occurred: '+(typeof err === 'string') ? err : JSON.stringify(err));
          
              });
```

**Comment by jleeson** [comment] 2023-09-27 03:23
I did some digging and you are not being rate limited, the rate limiter functions are properly catching a "failed" task but still operating at the specified speed. Additionally I tested this with a server I run and I was unable to replicate the error.

At some point during the backup process, discord.js is attempting to fetch a resource at a url where the resource either no longer exists or the server it exists on is currently offline. This is resulting in the error you are seeing. I am not sure at what point in the backup process this error is occurring, but I have been slowly improving this package over the original and hopefully will have better error reporting soon.

At this point there does not seem to be anything I can fix in the package to resolve this error, but to make sure, are you able to complete the backup despite the failed task? Does this error also occur on a fresh server?

**Comment by ColdbloodDK** [comment] 2023-09-27 03:51
the package isn't able to finish the backup, but don't crash the process, ill'try on a fresh new server

**Comment by jleeson** [comment] 2023-09-27 15:12
Interesting. I will do some more digging and see if I can reproduce it at all. Worst case ill improve error handling and then we can get an exact error for whats going wrong when you try to backup a server.

**Comment by ColdbloodDK** [comment] 2023-09-27 15:28
i suggest to add a verbose mode to the create and load method

**Comment by jleeson** [comment] 2023-09-27 15:30
@ColdbloodDK when testing with a new server did you try and load the backup from the original server or was it a backup of the new server? if possible can you provide the backup json file that caused the error?

**Comment by ColdbloodDK** [comment] 2023-09-27 15:34
this is the [https://discord.com/channels/940601936783228929/1082868084362199091/1156614595956441128](backup)

**Comment by ColdbloodDK** [comment] 2023-09-27 16:07
if i try with a new backup of a fresh server and load the backup of that server it works

**Comment by jleeson** [comment] 2023-09-27 16:15
> if i try with a new backup of a fresh server and load the backup of that server it works

Ok great, so the error is truly just discord.js failing to connect to an invalid url which is found somewhere in your server. I wont be able to resolve the problem on the package side, but I will try and get an update out quickly to at least enable it to report the failed task but continue with the process anyway.

**Comment by jleeson** [comment] 2023-09-27 22:26
@ColdbloodDK update your bot to use v0.5.8 of this package. this update includes the verbose option you suggested but more importantly the error reporting is significantly improved. if you try and load the backup again after updating it should report the exact function and data that it "failed to fetch" from there let me know what the new error is and Ill see if there is anything I can do to prevent the error from occuring.

**Comment by ColdbloodDK** [comment] 2023-09-28 18:48
the error is while downloading the guild icon for applying it on the new guild
```
Executing loadConfig::guild.setIcon.
Job Failed: fetch failed
ID: loadConfig::guild.setIcon
Completed loadConfig::guild.setIcon.
TypeError: fetch failed
    at fetch (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataResolver.resolveFile (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\util\DataResolver.js:125:21)
    at async DataResolver.resolveImage (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\util\DataResolver.js:68:18)
    at async Guild.edit (D:\Progetti\Software\Discord\discord-backupper\node_modules\discord.js\src\structures\Guild.js:854:24) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:182:24)
      at D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:129:46
      at Immediate._onImmediate (D:\Progetti\Software\Discord\discord-backupper\node_modules\undici\lib\core\connect.js:168:33)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

**Comment by jleeson** [comment] 2023-10-06 23:30
Given we have narrowed this down to the icon not working and im still unable to reproduce the problem using your backup file, and there is nothing I can change in the package to make it work on your end. I am going to close this issue. If you would like to continue debugging this and narrow down why it does not work on your machine specifically, I can reopen this.

**Closed by jleeson** 2023-10-06 23:30 UTC
